### PR TITLE
Implemented sprite draggable

### PR DESCRIPTION
**Pull request by loyaniu**
Implemented the bahavior that #83 mentioned.

### CODE REVIEW

**Comment by loyaniu** [comment]
**Here is a test demo:**

```python
from pystage.en import Sprite, Stage

stage = Stage()
sprite = stage.add_a_sprite()

def a():
    sprite.say("Able to be dragged!")
    sprite.set_drag_mode_draggable()

def b():
    sprite.say("Not able to be dragged!")
    sprite.set_drag_mode_not_draggable()

sprite.when_key_pressed("a", a)
sprite.when_key_pressed("b", b)

stage.play()
```

**Comment by kaiec** [comment]
Very good. We need a place for these demos. How about putting them into the documentation.

**Comment by loyaniu** [comment]
> Very good. We need a place for these demos. How about putting them into the documentation.

What do you mean putting them into the documentation? README?

**Comment by kaiec** [comment]
No, rather as example code for the block descriptions. Or as own section. I started to create these example projects that test and show the block implementations, but maybe we want to do this in a more structured and documented way. However, I don't have a string opinion on where to put this right now.

**Pull request merged**
