### PR TITLE
Fix say for secs

### LINKED ISSUE #37: Think/say for seconds
Need to implementing the think for seconds block and say for seconds block

def looks_thinkforsecs(self, text, secs):
        pass

 def looks_sayforsecs(self, text, secs):
        pass

### PR DESCRIPTION
**Pull request by brandenHusted**

### CODE REVIEW

**Comment by kaiec** [comment]
Fixes #37. Can you elaborate why you need the kill method? It seems to be created in this PR but not used.

**Comment by brandenHusted** [comment]
The Kill method was implemented so the text bubble would disappear from the screen after the ammount of seconds has passed.

**Comment by kaiec** [comment]
But where is it called?

**Comment by loyaniu** [comment]
I will make an another PR for this later. He didn't implement this, he just copied part of the code...

**Comment by kaiec** [comment]
Just add this to this PR. I assume there is some code missing from the code_block execution where the kill is called after the wait time has passed.

**Comment by loyaniu** [comment]
I put think and say for secs together, so...

> Just add this to this PR. I assume there is some code missing from the code_block execution where the kill is called after the wait time has passed.

**Pull request merged**
